// generated by stringer -type=TransactionType; DO NOT EDIT

package ofx

import "fmt"

const _TransactionType_name = "DEBITCREDIT"

var _TransactionType_index = [...]uint8{0, 5, 11}

func (i TransactionType) String() string {
	if i < 0 || i >= TransactionType(len(_TransactionType_index)-1) {
		return fmt.Sprintf("TransactionType(%d)", i)
	}
	return _TransactionType_name[_TransactionType_index[i]:_TransactionType_index[i+1]]
}
